#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-dm-aggregates
Version  : 1.2.0
Release  : 3
URL      : https://rubygems.org/downloads/dm-aggregates-1.2.0.gem
Source0  : https://rubygems.org/downloads/dm-aggregates-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-chronic_duration
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-dm-core
BuildRequires : rubygem-dm-migrations
BuildRequires : rubygem-jeweler
BuildRequires : rubygem-numerizer
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-spec

%description
dm-aggregates
=============
DataMapper plugin providing support for aggregates, functions on collections and datasets.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n dm-aggregates-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-dm-aggregates.gemspec

%build
gem build rubygem-dm-aggregates.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
dm-aggregates-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/dm-aggregates-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/dm-aggregates.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/adapters/dm-do-adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/aggregate_functions.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/core_ext/symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/functions.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/model.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/operators.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/query.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/repository.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/spec/isolated/require_after_setup_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/spec/isolated/require_before_setup_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/spec/isolated/require_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/spec/public/collection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/spec/public/model_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/spec/public/shared/aggregate_shared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/spec/rcov.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/spec/spec.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/tasks/spec.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/tasks/yard.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-aggregates-1.2.0/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.3.0/specifications/dm-aggregates-1.2.0.gemspec
