#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-dm-aggregates
Version  : 1.2.0
Release  : 1
URL      : https://rubygems.org/downloads/dm-aggregates-1.2.0.gem
Source0  : https://rubygems.org/downloads/dm-aggregates-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-chronic_duration
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-dm-core
BuildRequires : rubygem-dm-migrations
BuildRequires : rubygem-jeweler
BuildRequires : rubygem-numerizer
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-spec

%description
dm-aggregates
=============
DataMapper plugin providing support for aggregates, functions on collections and datasets.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n dm-aggregates-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-dm-aggregates.gemspec

%build
gem build rubygem-dm-aggregates.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
dm-aggregates-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/dm-aggregates-1.2.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Adapters/aggregate_extensions-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Adapters/aggregate_module-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Adapters/cdesc-Adapters.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Adapters/const_added-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Adapters/include_aggregate_api-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Collection/property_by_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/DataObjectsAdapter/aggregate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/DataObjectsAdapter/aggregate_field_statement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/DataObjectsAdapter/avg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/DataObjectsAdapter/cdesc-DataObjectsAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/DataObjectsAdapter/count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/DataObjectsAdapter/max-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/DataObjectsAdapter/min-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/DataObjectsAdapter/property_to_column_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/DataObjectsAdapter/sum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Functions/aggregate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Functions/assert_property_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Functions/avg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Functions/cdesc-Functions.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Functions/count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Functions/direction_map-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Functions/max-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Functions/min-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Functions/normalize_field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Functions/sum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Model/cdesc-Model.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Model/property_by_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Operators/avg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Operators/cdesc-Operators.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Operators/count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Operators/max-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Operators/min-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Operators/sum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Query/assert_valid_fields_with_operator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Query/cdesc-Query.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Query/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Repository/aggregate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/Repository/cdesc-Repository.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/cdesc-Aggregates.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/Aggregates/include_aggregate_api-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/DataMapper/cdesc-DataMapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/Symbol/cdesc-Symbol.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-aggregates-1.2.0/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/dm-aggregates.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/adapters/dm-do-adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/aggregate_functions.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/collection.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/core_ext/symbol.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/functions.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/model.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/operators.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/query.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/lib/dm-aggregates/repository.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/spec/isolated/require_after_setup_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/spec/isolated/require_before_setup_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/spec/isolated/require_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/spec/public/collection_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/spec/public/model_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/spec/public/shared/aggregate_shared_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/spec/rcov.opts
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/spec/spec.opts
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/tasks/spec.rake
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/tasks/yard.rake
/usr/lib64/ruby/gems/2.2.0/gems/dm-aggregates-1.2.0/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.2.0/specifications/dm-aggregates-1.2.0.gemspec
